#!/bin/bash

echo "$1" | su -c "steamos-readonly disable"
echo "$1" | su -c "rm -rf /etc/pacman.d/gnupg/ || :"
echo "$1" | su -c "pacman-key --init"
echo "$1" | su -c "pacman-key --populate"
echo "$1" | su -c "pacman -Sy --noconfirm --needed archlinux-keyring"
echo "$1" | su -c "pacman --noconfirm -S $(pacman -Qnkq | cut -d' ' -f1 | sort | uniq)"
echo "$1" | su -c "pacman --noconfirm -S base-devel multilib-devel --needed"
echo "$1" | su -c "pacman --noconfirm -S fakeroot git"
echo "$1" | su -c "touch /usr/share/steamos/devmode-enable"

